name: Create a release when pushing to a release branch.

on:
  push:
    branches:
      - '*_release*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: rlespinasse/github-slug-action@master

    - name: Create version number
      run: echo ::set-env name=VERSION::$(echo ${{ env.GITHUB_SHA_SHORT }})
    
    - name: Build the Docker image that creates the RFC-PDFs
      run: docker build $GITHUB_WORKSPACE/build -t time-machine-project/publish_pdfs

    - name: Create the output directories
      run:  mkdir -p releases
    
    - name: Create the release pdfs
      run: docker run -e VERSION=${{ env.VERSION }} -v $GITHUB_WORKSPACE/files/releases:/opt/input -v $GITHUB_WORKSPACE/releases:/opt/output time-machine-project/publish_pdfs

    - name: Zip the release pdfs
      run: zip -r -j released_rfcs.zip releases
    
    - name: Create a new release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.VERSION }}
        release_name: Release ${{ env.VERSION }} 
        draft: false
        prerelease: false

    - name: Upload released pdfs as release asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./released_rfcs.zip
        asset_name: released_rfcs.zip
        asset_content_type: application/zip
